app:
  textFile: "DataProcessor/src/main/resources/test.txt"   # Path to the text file
  outputFile: "DataProcessor/src/main/resources/output.txt"
  shardSize: 3                            # Shard size for splitting the text
  embeddingDim: 5